const data = {
  id: "",
  image: "",
  productName: "",
  price: "",
  rating: "",
  discount: "",
  brand: "",
  offers: "",
  bankOffer: "",
  availability: "",
  gender: "",
  size: "",
  sleeves: "",
  collar: "",
  fabric: "",
  pattern: "",
  occation: "",
  color: "",
  ram: "",
  internalStorage: "",
  batteryCapacity: "",
  screenSize: "",
  primaryCamera: "",
  secondaryCamera: "",
  processorBrand: "",
  resolutionType: "",
  operationSystem: "",
  networkType: "",
  simType: "",
  type: "",
  processor: "",
  processorGeneration: "",
  ramCapacity: "",
  ssdCapacity: "",
  operatingSystem: "",
  imagesList: [""],
};

//Cloths
//Mobile
//Laptop
